-- FjordSight PoC Schema Setup for Existing Snowflake Account
-- This script sets up the FjordSight schema in your existing database

-- Use your existing database
USE DATABASE dash_db_si;

-- Create the FjordSight schema
CREATE SCHEMA IF NOT EXISTS FJORDSIGHT_POC;
USE SCHEMA FJORDSIGHT_POC;

-- Create file formats
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_CHARACTER = '\\'
    NULL_IF = ('NULL', 'null', '', 'N/A');

-- Raw sensor data from MQTT streams
CREATE OR REPLACE TABLE RAW_SENSOR_DATA (
    TIMESTAMP TIMESTAMP_NTZ,
    FARM_LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SENSOR_TYPE VARCHAR(50),
    VALUE FLOAT,
    UNIT VARCHAR(20),
    QUALITY VARCHAR(20),
    DEVICE_ID VARCHAR(100),
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Harmonized farm data
CREATE OR REPLACE TABLE HARMONIZED_FARM_DATA (
    TIMESTAMP TIMESTAMP_NTZ,
    FARM_LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    WATER_TEMP_C FLOAT,
    OXYGEN_MG_L FLOAT,
    PH_LEVEL FLOAT,
    SALINITY_PPT FLOAT,
    TURBIDITY_NTU FLOAT,
    CURRENT_SPEED_MS FLOAT,
    FISH_ACTIVITY_INDEX FLOAT,
    FEED_INVENTORY_KG FLOAT,
    FISH_COUNT INT,
    AVERAGE_WEIGHT_KG FLOAT,
    MORTALITY_RATE FLOAT,
    FEED_CONVERSION_RATIO FLOAT,
    GROWTH_RATE_PERCENT FLOAT,
    AIR_TEMP_C FLOAT,
    WIND_SPEED_MS FLOAT,
    WAVE_HEIGHT_M FLOAT,
    DATA_COMPLETENESS_SCORE FLOAT,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- HAB risk predictions
CREATE OR REPLACE TABLE HAB_RISK_PREDICTIONS (
    PREDICTION_ID VARCHAR(100) PRIMARY KEY,
    TIMESTAMP TIMESTAMP_NTZ,
    FARM_LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    RISK_SCORE FLOAT,
    RISK_LEVEL VARCHAR(20),
    PREDICTION_HORIZON_HOURS INT,
    MODEL_VERSION VARCHAR(50),
    FEATURES VARIANT,
    CONTRIBUTING_FACTORS ARRAY,
    RECOMMENDATIONS ARRAY,
    ANOMALY_DETECTED BOOLEAN,
    ANOMALY_SCORE FLOAT,
    MODEL_CONFIDENCE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Customer profiles for Sales Co-Pilot
CREATE OR REPLACE TABLE CUSTOMER_PROFILES (
    CUSTOMER_ID VARCHAR(100) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    CUSTOMER_TYPE VARCHAR(50),
    LOCATION VARCHAR(100),
    PREFERRED_PRODUCTS ARRAY,
    AVERAGE_ORDER_SIZE_KG FLOAT,
    AVERAGE_ORDER_VALUE FLOAT,
    PURCHASE_FREQUENCY_DAYS INT,
    PROFITABILITY_TIER VARCHAR(20),
    RISK_TOLERANCE VARCHAR(20),
    QUALITY_REQUIREMENTS VARCHAR(100),
    PRICE_SENSITIVITY FLOAT,
    LAST_ORDER_DATE TIMESTAMP_NTZ,
    TOTAL_LIFETIME_VALUE FLOAT,
    RELATIONSHIP_SCORE FLOAT,
    NOTES VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Insert sample data
INSERT INTO HARMONIZED_FARM_DATA (
    TIMESTAMP, FARM_LOCATION, LATITUDE, LONGITUDE,
    WATER_TEMP_C, OXYGEN_MG_L, PH_LEVEL, SALINITY_PPT, TURBIDITY_NTU,
    CURRENT_SPEED_MS, FISH_ACTIVITY_INDEX, FEED_INVENTORY_KG,
    FISH_COUNT, AVERAGE_WEIGHT_KG, MORTALITY_RATE,
    FEED_CONVERSION_RATIO, GROWTH_RATE_PERCENT,
    AIR_TEMP_C, WIND_SPEED_MS, WAVE_HEIGHT_M, DATA_COMPLETENESS_SCORE
) VALUES
    (CURRENT_TIMESTAMP(), 'North Atlantic Site', 60.5, 5.3,
     12.5, 8.9, 7.6, 32.8, 1.8, 0.9, 0.65, 2500,
     10000, 4.2, 0.02, 1.4, 3.2, 8.0, 5.0, 1.2, 0.95),
    (CURRENT_TIMESTAMP(), 'Fjord Site Alpha', 61.2, 6.1,
     11.8, 9.2, 7.4, 31.9, 2.1, 0.7, 0.58, 2200,
     9800, 4.1, 0.025, 1.5, 3.0, 7.5, 4.8, 1.1, 0.92),
    (CURRENT_TIMESTAMP(), 'Deep Water Beta', 59.8, 4.9,
     13.1, 8.5, 7.8, 33.2, 1.5, 1.2, 0.72, 2800,
     10200, 4.3, 0.018, 1.3, 3.4, 8.5, 5.2, 1.3, 0.97);

-- Insert sample customer data
INSERT INTO CUSTOMER_PROFILES VALUES
    ('CUST_001', 'Nordic Seafood Restaurant Group', 'restaurant', 'Oslo, Norway',
     ARRAY_CONSTRUCT('Premium Atlantic Salmon', 'Organic Salmon'),
     150.0, 2250.0, 14, 'HIGH', 'MEDIUM', 'Premium Grade A+', 0.3,
     CURRENT_TIMESTAMP(), 45000.0, 4.5,
     PARSE_JSON('{"preferred_delivery": "Tuesday/Thursday", "special_requirements": "skin-on fillets"}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('CUST_002', 'Fjord Fish Distributors', 'distributor', 'Bergen, Norway',
     ARRAY_CONSTRUCT('Standard Atlantic Salmon', 'Whole Fish'),
     500.0, 6000.0, 7, 'MEDIUM', 'HIGH', 'Grade A', 0.6,
     CURRENT_TIMESTAMP(), 78000.0, 4.0,
     PARSE_JSON('{"volume_discounts": true, "flexible_delivery": true}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('CUST_003', 'Gourmet Market Chain', 'retailer', 'Stavanger, Norway',
     ARRAY_CONSTRUCT('Premium Atlantic Salmon', 'Smoked Salmon'),
     200.0, 3200.0, 10, 'HIGH', 'LOW', 'Premium Grade A+', 0.2,
     CURRENT_TIMESTAMP(), 52000.0, 4.2,
     PARSE_JSON('{"packaging": "retail-ready", "labeling": "organic certified"}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Create views for easy access
CREATE OR REPLACE VIEW LATEST_FARM_CONDITIONS AS
SELECT *
FROM HARMONIZED_FARM_DATA
WHERE TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
ORDER BY TIMESTAMP DESC, FARM_LOCATION;

SELECT 'FjordSight PoC schema setup completed successfully!' AS STATUS;
