-- FjordSight PoC Database Setup
-- Creates the database, schemas, and initial objects

-- Create database
CREATE DATABASE IF NOT EXISTS FJORDSIGHT_POC;
USE DATABASE FJORDSIGHT_POC;

-- Create schemas for different data zones
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS HARMONIZED_DATA;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ML_MODELS;

-- Set default schema
USE SCHEMA RAW_DATA;

-- Create file format for JSON data
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;

-- Create file format for CSV data
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_CHARACTER = '\\'
    NULL_IF = ('NULL', 'null', '', 'N/A');

GRANT USAGE ON DATABASE FJORDSIGHT_POC TO ROLE PUBLIC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FJORDSIGHT_POC TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN DATABASE FJORDSIGHT_POC TO ROLE PUBLIC;
GRANT SELECT ON FUTURE TABLES IN DATABASE FJORDSIGHT_POC TO ROLE PUBLIC;
