-- Harmonized Data Tables for FjordSight PoC
-- These tables combine and harmonize data from multiple sources

USE DATABASE FJORDSIGHT_POC;
USE SCHEMA HARMONIZED_DATA;

-- Main harmonized table combining IT/OT data
CREATE OR REPLACE TABLE HARMONIZED_FARM_DATA (
    TIMESTAMP TIMESTAMP_NTZ,
    FARM_LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    -- Environmental sensors (OT data)
    WATER_TEMP_C FLOAT,
    OXYGEN_MG_L FLOAT,
    PH_LEVEL FLOAT,
    SALINITY_PPT FLOAT,
    TURBIDITY_NTU FLOAT,
    CURRENT_SPEED_MS FLOAT,
    FISH_ACTIVITY_INDEX FLOAT,
    -- Production data (IT data from ERP)
    FEED_INVENTORY_KG FLOAT,
    FISH_COUNT INT,
    AVERAGE_WEIGHT_KG FLOAT,
    MORTALITY_RATE FLOAT,
    FEED_CONVERSION_RATIO FLOAT,
    GROWTH_RATE_PERCENT FLOAT,
    -- External data enrichment
    AIR_TEMP_C FLOAT,
    WIND_SPEED_MS FLOAT,
    WAVE_HEIGHT_M FLOAT,
    -- Data quality and metadata
    DATA_COMPLETENESS_SCORE FLOAT,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CLUSTER BY (DATE_TRUNC('hour', TIMESTAMP), FARM_LOCATION)
);

-- Create view for real-time unified IT/OT data
CREATE OR REPLACE VIEW UNIFIED_IT_OT_DATA AS
SELECT 
    DATE_TRUNC('hour', s.TIMESTAMP) as TIMESTAMP,
    s.FARM_LOCATION,
    s.LATITUDE,
    s.LONGITUDE,
    -- OT Data (Sensor readings pivoted)
    AVG(CASE WHEN s.SENSOR_TYPE = 'water_temp' THEN s.VALUE END) as WATER_TEMP_C,
    AVG(CASE WHEN s.SENSOR_TYPE = 'oxygen' THEN s.VALUE END) as OXYGEN_MG_L,
    AVG(CASE WHEN s.SENSOR_TYPE = 'ph' THEN s.VALUE END) as PH_LEVEL,
    AVG(CASE WHEN s.SENSOR_TYPE = 'salinity' THEN s.VALUE END) as SALINITY_PPT,
    AVG(CASE WHEN s.SENSOR_TYPE = 'turbidity' THEN s.VALUE END) as TURBIDITY_NTU,
    AVG(CASE WHEN s.SENSOR_TYPE = 'current_speed' THEN s.VALUE END) as CURRENT_SPEED_MS,
    AVG(CASE WHEN s.SENSOR_TYPE = 'fish_activity' THEN s.VALUE END) as FISH_ACTIVITY_INDEX,
    -- IT Data (ERP data - latest values)
    MAX(CASE WHEN e.DATA_TYPE = 'feed_inventory' THEN e.FEED_QUANTITY_KG END) as FEED_INVENTORY_KG,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.FISH_COUNT END) as FISH_COUNT,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.AVERAGE_WEIGHT_KG END) as AVERAGE_WEIGHT_KG,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.GROWTH_RATE_PERCENT END) as GROWTH_RATE_PERCENT,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.MORTALITY_RATE END) as MORTALITY_RATE,
    -- Data quality metrics
    COUNT(DISTINCT s.SENSOR_TYPE) as SENSOR_TYPES_COUNT,
    COUNT(s.VALUE) as SENSOR_READINGS_COUNT,
    AVG(CASE WHEN s.QUALITY = 'good' THEN 1.0 ELSE 0.5 END) as DATA_COMPLETENESS_SCORE,
    CURRENT_TIMESTAMP() as LAST_UPDATED
FROM RAW_SENSOR_DATA s
LEFT JOIN RAW_ERP_DATA e ON s.FARM_LOCATION = e.LOCATION
    AND DATE_TRUNC('day', s.TIMESTAMP) = DATE_TRUNC('day', e.TIMESTAMP)
WHERE s.TIMESTAMP >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND s.QUALITY IN ('good', 'warning')
GROUP BY 
    DATE_TRUNC('hour', s.TIMESTAMP),
    s.FARM_LOCATION,
    s.LATITUDE,
    s.LONGITUDE;

-- Create Dynamic Table for real-time IT/OT data harmonization
-- This automatically refreshes as new data arrives, demonstrating Snowflake's automated processing
CREATE OR REPLACE DYNAMIC TABLE HARMONIZED_FARM_DATA_DT
TARGET_LAG = '1 minute'
WAREHOUSE = aicollege
AS
SELECT 
    DATE_TRUNC('minute', s.TIMESTAMP) as TIMESTAMP,
    s.FARM_LOCATION,
    s.LATITUDE,
    s.LONGITUDE,
    -- OT Data (Operational Technology) - Environmental sensors from MQTT
    AVG(CASE WHEN s.SENSOR_TYPE = 'water_temp' THEN s.VALUE END) as WATER_TEMP_C,
    AVG(CASE WHEN s.SENSOR_TYPE = 'oxygen' THEN s.VALUE END) as OXYGEN_MG_L,
    AVG(CASE WHEN s.SENSOR_TYPE = 'ph' THEN s.VALUE END) as PH_LEVEL,
    AVG(CASE WHEN s.SENSOR_TYPE = 'salinity' THEN s.VALUE END) as SALINITY_PPT,
    AVG(CASE WHEN s.SENSOR_TYPE = 'turbidity' THEN s.VALUE END) as TURBIDITY_NTU,
    AVG(CASE WHEN s.SENSOR_TYPE = 'current_speed' THEN s.VALUE END) as CURRENT_SPEED_MS,
    AVG(CASE WHEN s.SENSOR_TYPE = 'fish_activity' THEN s.VALUE END) as FISH_ACTIVITY_INDEX,
    -- IT Data (Information Technology) - Production data from ERP systems
    MAX(CASE WHEN e.DATA_TYPE = 'feed_inventory' THEN e.FEED_QUANTITY_KG END) as FEED_INVENTORY_KG,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.FISH_COUNT END) as FISH_COUNT,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.AVERAGE_WEIGHT_KG END) as AVERAGE_WEIGHT_KG,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.GROWTH_RATE_PERCENT END) as GROWTH_RATE_PERCENT,
    MAX(CASE WHEN e.DATA_TYPE = 'production_metrics' THEN e.MORTALITY_RATE END) as MORTALITY_RATE,
    -- Data quality and automation metrics
    COUNT(DISTINCT s.SENSOR_TYPE) as SENSOR_TYPES_AVAILABLE,
    COUNT(s.VALUE) as SENSOR_READINGS_COUNT,
    AVG(CASE WHEN s.QUALITY = 'good' THEN 1.0 ELSE 0.5 END) as DATA_COMPLETENESS_SCORE,
    CURRENT_TIMESTAMP() as LAST_UPDATED
FROM RAW_SENSOR_DATA s
LEFT JOIN RAW_ERP_DATA e ON s.FARM_LOCATION = e.LOCATION
    AND DATE_TRUNC('hour', s.TIMESTAMP) = DATE_TRUNC('hour', e.TIMESTAMP)
WHERE s.TIMESTAMP >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND s.QUALITY IN ('good', 'warning')
GROUP BY 
    DATE_TRUNC('minute', s.TIMESTAMP),
    s.FARM_LOCATION,
    s.LATITUDE,
    s.LONGITUDE;

-- Create a view for easy access to latest harmonized data
CREATE OR REPLACE VIEW LATEST_HARMONIZED_DATA AS
SELECT * 
FROM HARMONIZED_FARM_DATA_DT
WHERE TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
ORDER BY TIMESTAMP DESC, FARM_LOCATION;

-- Task to enrich with external/marketplace data
CREATE OR REPLACE TASK ENRICH_WITH_EXTERNAL_DATA
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 minutes'
    AFTER ENRICH_WITH_ERP_DATA
AS
MERGE INTO HARMONIZED_FARM_DATA h
USING (
    SELECT 
        e.TIMESTAMP,
        e.LOCATION as FARM_LOCATION,
        e.DATA_JSON:temperature::FLOAT as AIR_TEMP_C,
        e.DATA_JSON:wind_speed::FLOAT as WIND_SPEED_MS,
        e.DATA_JSON:wave_height::FLOAT as WAVE_HEIGHT_M
    FROM RAW_DATA.EXTERNAL_DATA_STREAM e
    WHERE e.METADATA$ACTION = 'INSERT'
      AND e.DATA_SOURCE = 'openweather'
) ext
ON h.FARM_LOCATION = ext.FARM_LOCATION 
   AND DATE_TRUNC('hour', h.TIMESTAMP) = DATE_TRUNC('hour', ext.TIMESTAMP)
WHEN MATCHED THEN UPDATE SET
    h.AIR_TEMP_C = ext.AIR_TEMP_C,
    h.WIND_SPEED_MS = ext.WIND_SPEED_MS,
    h.WAVE_HEIGHT_M = ext.WAVE_HEIGHT_M,
    h.LAST_UPDATED = CURRENT_TIMESTAMP();

-- Start the tasks
ALTER TASK ENRICH_WITH_ERP_DATA RESUME;
ALTER TASK ENRICH_WITH_EXTERNAL_DATA RESUME;

-- Create views for easy access
CREATE OR REPLACE VIEW LATEST_FARM_CONDITIONS AS
SELECT *
FROM HARMONIZED_FARM_DATA
WHERE TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
ORDER BY TIMESTAMP DESC, FARM_LOCATION;

CREATE OR REPLACE VIEW FARM_HEALTH_SUMMARY AS
SELECT 
    FARM_LOCATION,
    AVG(WATER_TEMP_C) as AVG_WATER_TEMP,
    AVG(OXYGEN_MG_L) as AVG_OXYGEN,
    AVG(PH_LEVEL) as AVG_PH,
    AVG(MORTALITY_RATE) as AVG_MORTALITY_RATE,
    AVG(GROWTH_RATE_PERCENT) as AVG_GROWTH_RATE,
    COUNT(*) as MEASUREMENT_COUNT,
    MAX(TIMESTAMP) as LAST_MEASUREMENT
FROM HARMONIZED_FARM_DATA
WHERE TIMESTAMP >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY FARM_LOCATION;
