-- ML Models and Analytics Tables for FjordSight PoC
-- Tables for storing ML model results and analytics

USE DATABASE FJORDSIGHT_POC;
USE SCHEMA ML_MODELS;

-- HAB risk predictions table
CREATE OR REPLACE TABLE HAB_RISK_PREDICTIONS (
    PREDICTION_ID VARCHAR(100) PRIMARY KEY,
    TIMESTAMP TIMESTAMP_NTZ,
    FARM_LOCATION VARCHAR(100),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    RISK_SCORE FLOAT,
    RISK_LEVEL VARCHAR(20), -- LOW, MEDIUM, HIGH
    PREDICTION_HORIZON_HOURS INT,
    MODEL_VERSION VARCHAR(50),
    FEATURES VARIANT, -- JSON object with input features
    CONTRIBUTING_FACTORS ARRAY, -- Array of risk factor descriptions
    RECOMMENDATIONS ARRAY, -- Array of recommended actions
    ANOMALY_DETECTED BOOLEAN,
    ANOMALY_SCORE FLOAT,
    MODEL_CONFIDENCE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CLUSTER BY (FARM_LOCATION, DATE_TRUNC('day', TIMESTAMP))
);

-- Sales opportunity predictions (for AI Sales Co-Pilot)
CREATE OR REPLACE TABLE SALES_OPPORTUNITY_PREDICTIONS (
    OPPORTUNITY_ID VARCHAR(100) PRIMARY KEY,
    TIMESTAMP TIMESTAMP_NTZ,
    CUSTOMER_ID VARCHAR(100),
    CUSTOMER_NAME VARCHAR(200),
    PRODUCT_TYPE VARCHAR(100),
    PREDICTED_VOLUME_KG FLOAT,
    PREDICTED_REVENUE FLOAT,
    PROBABILITY_SCORE FLOAT,
    PROFITABILITY_RANK INT,
    HISTORICAL_PREFERENCE_SCORE FLOAT,
    RISK_SCORE FLOAT,
    RECOMMENDATION_REASON VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CLUSTER BY (DATE_TRUNC('day', TIMESTAMP), CUSTOMER_ID)
);

-- Model performance metrics
CREATE OR REPLACE TABLE MODEL_PERFORMANCE_METRICS (
    METRIC_ID VARCHAR(100) PRIMARY KEY,
    MODEL_NAME VARCHAR(100),
    MODEL_VERSION VARCHAR(50),
    METRIC_TYPE VARCHAR(50), -- 'accuracy', 'precision', 'recall', 'f1_score', 'mse', 'r2'
    METRIC_VALUE FLOAT,
    EVALUATION_DATE TIMESTAMP_NTZ,
    DATA_PERIOD_START TIMESTAMP_NTZ,
    DATA_PERIOD_END TIMESTAMP_NTZ,
    SAMPLE_SIZE INT,
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Customer data for Sales Co-Pilot
CREATE OR REPLACE TABLE CUSTOMER_PROFILES (
    CUSTOMER_ID VARCHAR(100) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200),
    CUSTOMER_TYPE VARCHAR(50), -- 'restaurant', 'retailer', 'distributor'
    LOCATION VARCHAR(100),
    PREFERRED_PRODUCTS ARRAY,
    AVERAGE_ORDER_SIZE_KG FLOAT,
    AVERAGE_ORDER_VALUE FLOAT,
    PURCHASE_FREQUENCY_DAYS INT,
    PROFITABILITY_TIER VARCHAR(20), -- 'HIGH', 'MEDIUM', 'LOW'
    RISK_TOLERANCE VARCHAR(20), -- 'HIGH', 'MEDIUM', 'LOW'
    QUALITY_REQUIREMENTS VARCHAR(100),
    PRICE_SENSITIVITY FLOAT, -- 0-1 scale
    LAST_ORDER_DATE TIMESTAMP_NTZ,
    TOTAL_LIFETIME_VALUE FLOAT,
    RELATIONSHIP_SCORE FLOAT, -- 0-1 scale
    NOTES VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Historical sales data
CREATE OR REPLACE TABLE SALES_HISTORY (
    SALE_ID VARCHAR(100) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(100),
    FARM_LOCATION VARCHAR(100),
    PRODUCT_TYPE VARCHAR(100),
    VOLUME_KG FLOAT,
    PRICE_PER_KG FLOAT,
    TOTAL_REVENUE FLOAT,
    SALE_DATE TIMESTAMP_NTZ,
    DELIVERY_DATE TIMESTAMP_NTZ,
    QUALITY_GRADE VARCHAR(20),
    CUSTOMER_SATISFACTION_SCORE FLOAT,
    PROFIT_MARGIN FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CLUSTER BY (DATE_TRUNC('month', SALE_DATE), CUSTOMER_ID)
);

-- Insert sample customer data
INSERT INTO CUSTOMER_PROFILES VALUES
    ('CUST_001', 'Nordic Seafood Restaurant Group', 'restaurant', 'Oslo, Norway', 
     ARRAY_CONSTRUCT('Premium Atlantic Salmon', 'Organic Salmon'), 
     150.0, 2250.0, 14, 'HIGH', 'MEDIUM', 'Premium Grade A+', 0.3, 
     '2024-01-10', 45000.0, 0.9, 
     PARSE_JSON('{"preferred_delivery": "Tuesday/Thursday", "special_requirements": "skin-on fillets"}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
     
    ('CUST_002', 'Fjord Fish Distributors', 'distributor', 'Bergen, Norway',
     ARRAY_CONSTRUCT('Standard Atlantic Salmon', 'Whole Fish'),
     500.0, 6000.0, 7, 'MEDIUM', 'HIGH', 'Grade A', 0.6,
     '2024-01-12', 78000.0, 0.8,
     PARSE_JSON('{"volume_discounts": true, "flexible_delivery": true}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
     
    ('CUST_003', 'Gourmet Market Chain', 'retailer', 'Stavanger, Norway',
     ARRAY_CONSTRUCT('Premium Atlantic Salmon', 'Smoked Salmon'),
     200.0, 3200.0, 10, 'HIGH', 'LOW', 'Premium Grade A+', 0.2,
     '2024-01-08', 52000.0, 0.85,
     PARSE_JSON('{"packaging": "retail-ready", "labeling": "organic certified"}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
     
    ('CUST_004', 'Export Trading Company', 'distributor', 'International',
     ARRAY_CONSTRUCT('Standard Atlantic Salmon', 'Frozen Fillets'),
     1000.0, 11000.0, 21, 'MEDIUM', 'HIGH', 'Grade A', 0.7,
     '2024-01-05', 125000.0, 0.7,
     PARSE_JSON('{"export_documentation": true, "container_shipping": true}'),
     CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- Insert sample sales history
INSERT INTO SALES_HISTORY VALUES
    ('SALE_001', 'CUST_001', 'North Atlantic Site', 'Premium Atlantic Salmon', 
     150.0, 15.0, 2250.0, '2024-01-10', '2024-01-11', 'A+', 4.8, 0.35, CURRENT_TIMESTAMP()),
    ('SALE_002', 'CUST_002', 'Fjord Site Alpha', 'Standard Atlantic Salmon',
     500.0, 12.0, 6000.0, '2024-01-12', '2024-01-13', 'A', 4.5, 0.28, CURRENT_TIMESTAMP()),
    ('SALE_003', 'CUST_003', 'North Atlantic Site', 'Premium Atlantic Salmon',
     200.0, 16.0, 3200.0, '2024-01-08', '2024-01-09', 'A+', 4.9, 0.38, CURRENT_TIMESTAMP());

-- Create views for analytics
CREATE OR REPLACE VIEW CURRENT_HAB_RISKS AS
SELECT 
    p.*,
    h.WATER_TEMP_C,
    h.OXYGEN_MG_L,
    h.PH_LEVEL,
    h.TURBIDITY_NTU
FROM HAB_RISK_PREDICTIONS p
LEFT JOIN HARMONIZED_DATA.HARMONIZED_FARM_DATA h
    ON p.FARM_LOCATION = h.FARM_LOCATION
    AND ABS(DATEDIFF('minute', p.TIMESTAMP, h.TIMESTAMP)) <= 30
WHERE p.CREATED_AT >= DATEADD('hour', -2, CURRENT_TIMESTAMP())
ORDER BY p.RISK_SCORE DESC;

CREATE OR REPLACE VIEW TOP_SALES_OPPORTUNITIES AS
SELECT 
    s.*,
    c.CUSTOMER_NAME,
    c.CUSTOMER_TYPE,
    c.PROFITABILITY_TIER,
    c.RELATIONSHIP_SCORE
FROM SALES_OPPORTUNITY_PREDICTIONS s
JOIN CUSTOMER_PROFILES c ON s.CUSTOMER_ID = c.CUSTOMER_ID
WHERE s.CREATED_AT >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
ORDER BY s.PROBABILITY_SCORE * s.PREDICTED_REVENUE DESC;

-- Create stored procedure for generating sales recommendations
CREATE OR REPLACE PROCEDURE GENERATE_SALES_RECOMMENDATIONS(
    AVAILABLE_VOLUME_KG FLOAT,
    PRODUCT_TYPE VARCHAR
)
RETURNS TABLE (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    RECOMMENDED_VOLUME_KG FLOAT,
    EXPECTED_REVENUE FLOAT,
    PROBABILITY_SCORE FLOAT,
    RECOMMENDATION_RANK INT
)
LANGUAGE SQL
AS
$$
BEGIN
    -- Create temporary table with customer scoring
    CREATE OR REPLACE TEMPORARY TABLE CUSTOMER_SCORES AS
    SELECT 
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.AVERAGE_ORDER_SIZE_KG,
        c.AVERAGE_ORDER_VALUE / c.AVERAGE_ORDER_SIZE_KG as PRICE_PER_KG,
        c.PROFITABILITY_TIER,
        c.RELATIONSHIP_SCORE,
        c.RISK_TOLERANCE,
        -- Calculate volume they might want
        LEAST(AVAILABLE_VOLUME_KG * 0.4, c.AVERAGE_ORDER_SIZE_KG * 1.2) as RECOMMENDED_VOLUME,
        -- Calculate probability based on historical patterns and preferences
        CASE 
            WHEN ARRAY_CONTAINS(PRODUCT_TYPE::VARIANT, c.PREFERRED_PRODUCTS) THEN 0.8
            ELSE 0.4
        END * c.RELATIONSHIP_SCORE as BASE_PROBABILITY,
        -- Adjust for recency of last order
        CASE 
            WHEN DATEDIFF('day', c.LAST_ORDER_DATE, CURRENT_DATE()) <= c.PURCHASE_FREQUENCY_DAYS THEN 0.9
            WHEN DATEDIFF('day', c.LAST_ORDER_DATE, CURRENT_DATE()) <= c.PURCHASE_FREQUENCY_DAYS * 1.5 THEN 1.2
            ELSE 0.7
        END as RECENCY_MULTIPLIER
    FROM CUSTOMER_PROFILES c
    WHERE c.CUSTOMER_ID IS NOT NULL;
    
    -- Return ranked recommendations
    LET result_cursor CURSOR FOR
    SELECT 
        CUSTOMER_ID,
        CUSTOMER_NAME,
        RECOMMENDED_VOLUME as RECOMMENDED_VOLUME_KG,
        RECOMMENDED_VOLUME * PRICE_PER_KG as EXPECTED_REVENUE,
        LEAST(BASE_PROBABILITY * RECENCY_MULTIPLIER, 1.0) as PROBABILITY_SCORE,
        ROW_NUMBER() OVER (ORDER BY 
            (BASE_PROBABILITY * RECENCY_MULTIPLIER) * (RECOMMENDED_VOLUME * PRICE_PER_KG) DESC
        ) as RECOMMENDATION_RANK
    FROM CUSTOMER_SCORES
    ORDER BY RECOMMENDATION_RANK
    LIMIT 10;
    
    RETURN TABLE(result_cursor);
END;
$$;
